-- 先扩展再发布应用；旧二进制仍可插入不带恢复字段的任务。
ALTER TABLE KNOWLEDGE_INGESTION_JOB ADD COLUMN RETRY_COUNT INTEGER NOT NULL DEFAULT 0 COMMENT '已使用的自动重试次数';
ALTER TABLE KNOWLEDGE_INGESTION_JOB ADD COLUMN NEXT_RETRY_AT TIMESTAMP NULL COMMENT '下次允许自动重试的时间';
ALTER TABLE KNOWLEDGE_INGESTION_JOB ADD COLUMN ERROR_CODE VARCHAR(64) NULL COMMENT '可公开的稳定错误码';
ALTER TABLE KNOWLEDGE_INGESTION_JOB ADD COLUMN FAILED_STAGE VARCHAR(32) NULL COMMENT '失败的准备阶段或存储目标';
ALTER TABLE KNOWLEDGE_INGESTION_JOB ADD COLUMN LEASE_OWNER VARCHAR(128) NULL COMMENT '本次执行的唯一租约持有者';
ALTER TABLE KNOWLEDGE_INGESTION_JOB ADD COLUMN LEASE_UNTIL TIMESTAMP NULL COMMENT '租约到期时间，续期同时推进revision';
CREATE INDEX IDX_INGESTION_RECOVERY ON KNOWLEDGE_INGESTION_JOB (STATUS, NEXT_RETRY_AT, LEASE_UNTIL);
