CREATE TABLE IF NOT EXISTS USERS (
  USERNAME VARCHAR(128) NOT NULL PRIMARY KEY,
  PASSWORD_HASH VARCHAR(256) NOT NULL,
  TENANT VARCHAR(128) NOT NULL,
  USER_ID VARCHAR(128) NOT NULL,
  SCOPES VARCHAR(1024),
  ROLES VARCHAR(1024),
  ENABLED BOOLEAN NOT NULL,
  VERSION BIGINT NOT NULL DEFAULT 0,
  CREATED_AT BIGINT NOT NULL
);

CREATE TABLE IF NOT EXISTS USER_ROLE (
  USERNAME VARCHAR(128) NOT NULL,
  ROLE_NAME VARCHAR(128) NOT NULL,
  CREATED_AT BIGINT NOT NULL,
  PRIMARY KEY (USERNAME, ROLE_NAME)
);

CREATE TABLE IF NOT EXISTS ROLES (
  NAME VARCHAR(128) NOT NULL PRIMARY KEY,
  SCOPES VARCHAR(1024),
  DESCRIPTION VARCHAR(256),
  VERSION BIGINT NOT NULL DEFAULT 0,
  CREATED_AT BIGINT NOT NULL
);

CREATE TABLE IF NOT EXISTS ROLE_SCOPE (
  ROLE_NAME VARCHAR(128) NOT NULL,
  SCOPE VARCHAR(128) NOT NULL,
  CREATED_AT BIGINT NOT NULL,
  PRIMARY KEY (ROLE_NAME, SCOPE)
);

CREATE TABLE IF NOT EXISTS AUTH_SESSION (
  TOKEN_HASH VARCHAR(128) NOT NULL PRIMARY KEY,
  USERNAME VARCHAR(128) NOT NULL,
  CREATED_AT BIGINT NOT NULL,
  EXPIRES_AT BIGINT NOT NULL,
  REVOKED BOOLEAN NOT NULL
);

CREATE TABLE IF NOT EXISTS AUTH_GROUP (
  NAME VARCHAR(128) NOT NULL PRIMARY KEY,
  DESCRIPTION VARCHAR(256),
  VERSION BIGINT NOT NULL DEFAULT 0,
  CREATED_AT BIGINT NOT NULL
);

CREATE TABLE IF NOT EXISTS GROUP_ROLE (
  GROUP_NAME VARCHAR(128) NOT NULL,
  ROLE_NAME VARCHAR(128) NOT NULL,
  CREATED_AT BIGINT NOT NULL,
  PRIMARY KEY (GROUP_NAME, ROLE_NAME)
);

CREATE TABLE IF NOT EXISTS USER_GROUP (
  USERNAME VARCHAR(128) NOT NULL,
  GROUP_NAME VARCHAR(128) NOT NULL,
  CREATED_AT BIGINT NOT NULL,
  PRIMARY KEY (USERNAME, GROUP_NAME)
);

CREATE TABLE IF NOT EXISTS TENANT_POLICY (
  TENANT VARCHAR(128) NOT NULL PRIMARY KEY,
  VERSION BIGINT NOT NULL DEFAULT 0,
  UPDATED_AT BIGINT NOT NULL
);

CREATE TABLE IF NOT EXISTS TENANT_ROLE (
  TENANT VARCHAR(128) NOT NULL,
  ROLE_NAME VARCHAR(128) NOT NULL,
  CREATED_AT BIGINT NOT NULL,
  PRIMARY KEY (TENANT, ROLE_NAME)
);
