CREATE TABLE IF NOT EXISTS WF_REPLY (
  INSTANCE_ID VARCHAR(64) NOT NULL PRIMARY KEY,
  REPLY MEDIUMTEXT,
  DEGRADED TINYINT NOT NULL DEFAULT 0,
  UPDATED_AT BIGINT NOT NULL
);

CREATE TABLE IF NOT EXISTS WF_IDEMPOTENCY (
  TENANT_ID VARCHAR(128) NOT NULL,
  OPERATION_NAME VARCHAR(64) NOT NULL,
  IDEMPOTENCY_KEY_HASH CHAR(64) NOT NULL,
  REQUEST_HASH CHAR(64) NOT NULL,
  BUSINESS_KEY VARCHAR(512) NOT NULL,
  INSTANCE_ID VARCHAR(64),
  CREATED_AT BIGINT NOT NULL,
  UPDATED_AT BIGINT NOT NULL,
  PRIMARY KEY (TENANT_ID, OPERATION_NAME, IDEMPOTENCY_KEY_HASH)
);

CREATE TABLE IF NOT EXISTS WF_OUTBOX (
  INSTANCE_ID VARCHAR(64) NOT NULL PRIMARY KEY,
  TENANT_ID VARCHAR(64),
  TARGET_URL VARCHAR(1024) NOT NULL,
  STATUS VARCHAR(16) NOT NULL,
  ATTEMPTS INT NOT NULL DEFAULT 0,
  NEXT_ATTEMPT_AT BIGINT NOT NULL,
  LAST_ERROR VARCHAR(512),
  CLAIMED_BY VARCHAR(128),
  CLAIMED_UNTIL BIGINT,
  CREATED_AT BIGINT NOT NULL,
  UPDATED_AT BIGINT NOT NULL
);

CREATE TABLE IF NOT EXISTS WF_TERMINAL_EVENT_OUTBOX (
  INSTANCE_ID VARCHAR(64) NOT NULL PRIMARY KEY,
  TENANT_ID VARCHAR(64),
  CHAT_ID VARCHAR(128),
  OUTCOME VARCHAR(32),
  WEBHOOK_URL VARCHAR(1024),
  STATUS VARCHAR(16) NOT NULL,
  ATTEMPTS INT NOT NULL DEFAULT 0,
  NEXT_ATTEMPT_AT BIGINT NOT NULL,
  LAST_ERROR VARCHAR(512),
  CLAIMED_BY VARCHAR(128),
  CLAIMED_UNTIL BIGINT,
  CREATED_AT BIGINT NOT NULL,
  UPDATED_AT BIGINT NOT NULL
);
