CREATE TABLE IF NOT EXISTS RAG_GRAPH_TRIPLE (
  GRAPH_ID VARCHAR(128) NOT NULL PRIMARY KEY,
  TENANT_ID VARCHAR(128) NOT NULL,
  CATEGORY VARCHAR(128),
  SUBJECT_TEXT VARCHAR(512) NOT NULL,
  SUBJECT_KEY VARCHAR(512) NOT NULL,
  RELATION_TEXT VARCHAR(256) NOT NULL,
  OBJECT_TEXT VARCHAR(512) NOT NULL,
  OBJECT_KEY VARCHAR(512) NOT NULL,
  SOURCE_ID VARCHAR(512),
  CREATED_AT BIGINT NOT NULL
);
