#!/usr/bin/env python3
"""从未插值的 Compose 模型生成接入覆盖文件，避免把本机凭据写入仓库。"""
import json, pathlib, re, subprocess
ROOT=pathlib.Path(__file__).resolve().parents[2]
model=json.loads(subprocess.check_output(['docker','compose','-f',str(ROOT/'deploy/docker-compose.yml'),
    '-f',str(ROOT/'deploy/docker-compose.knowledge-split.yml'),'config','--no-interpolate','--format','json']))
DB={'auth':'auth','async_task':'async','flowable':'workflow','knowledge_graph':'graph','knowledge_ingestion':'ingest',
    'order_service':'order','channel':'channel','nl2sql_demo':'analytics'}
USERS={'auth_app':('auth','APP'),'async_task_app':('async','APP'),'workflow_app':('workflow','APP'),
    'knowledge_graph_app':('graph','APP'),'knowledge_ingestion_app':('ingest','APP'),'order_app':('order','APP'),
    'channel_app':('channel','APP'),'nl2sql_ro':('analytics','APP'),
    'auth_migrator':('auth','MIGRATOR'),'async_task_migrator':('async','MIGRATOR'),'workflow_migrator':('workflow','MIGRATOR'),
    'knowledge_graph_migrator':('graph','MIGRATOR'),'knowledge_ingestion_migrator':('ingest','MIGRATOR'),
    'order_migrator':('order','MIGRATOR'),'channel_migrator':('channel','MIGRATOR'),'analytics_demo_migrator':('analytics','MIGRATOR')}
LOCAL={'mysql','redis','kafka','litellm-postgres','qdrant','elasticsearch','kibana','jaeger','minio','minio-init'}
common={'SPRING_DATA_REDIS_HOST':'infra-redis7','SPRING_DATA_REDIS_PORT':'6379','SPRING_DATA_REDIS_USERNAME':'lc4j',
    'SPRING_DATA_REDIS_PASSWORD':'${LC4J_REDIS_PASSWORD:?run dev-infra provision}', 'PLATFORM_REDIS_KEY_PREFIX':'lc4j:',
    'APP_RATE_LIMIT_REDIS_KEY_PREFIX':'lc4j:rate:limit:','APP_TOKEN_BUDGET_REDIS_KEY_PREFIX':'lc4j:token:budget:',
    'APP_COST_REDIS_KEY_PREFIX':'lc4j:cost:usd:', 'KAFKA_BOOTSTRAP_SERVERS':'infra-kafka38:9092',
    'SPRING_KAFKA_BOOTSTRAP_SERVERS':'infra-kafka38:9092','PLATFORM_EVENTBUS_TOPIC_PREFIX':'lc4j.',
    'MANAGEMENT_OTLP_TRACING_ENDPOINT':'http://infra-otel-collector:4318/v1/traces'}
lines=['# Generated by deploy/dev-infra/generate.py. No credentials; existing local infra is opt-in only.','services:']
for name,service in model['services'].items():
    lines.append('  '+name+':')
    if name in LOCAL:
        lines.append('    profiles: !override ["local-infra"]');continue
    if name in {'knowledge-query','knowledge-ingest-api','knowledge-ingest-worker'}:lines.append('    profiles: ["split"]')
    lines.append('    networks: ["default", "dev-infra"]')
    if not name.startswith('migrate-'):lines.append('    restart: unless-stopped')
    deps={k:v for k,v in service.get('depends_on',{}).items() if k not in LOCAL}
    if name.startswith('knowledge-'): deps['migrate-knowledge-ingestion']={'condition':'service_completed_successfully','required':True}
    lines.append('    depends_on: !override '+json.dumps(deps))
    env=dict(common)
    original=service.get('environment',{})
    if not isinstance(original,dict): original={}
    for key,value in original.items():
        if not isinstance(value,str):continue
        match=re.search(r'jdbc:mysql://mysql:3306/([a-z0-9_]+)',value)
        if match and match.group(1) in DB:env[key]=value.replace('mysql:3306/'+match.group(1),'infra-mysql84:3306/lc4j_'+match.group(1))
        if value in USERS:
            short,role=USERS[value];env[key]=f'lc4j_{short}_{role.lower()}'
            pwd_key=re.sub(r'_(USER|USERNAME)$','_PASSWORD',key)
            env[pwd_key]='${LC4J_'+short.upper()+'_'+role+'_PASSWORD:?run dev-infra provision}'
        if 'http://jaeger:4318' in value:env[key]=value.replace('http://jaeger:4318','http://infra-otel-collector:4318')
    env['PLATFORM_EVENTBUS_CONSUMER_GROUP_ID']='lc4j.'+name
    env['SPRING_KAFKA_CONSUMER_GROUP_ID']='lc4j.'+name
    if name=='channel-service':
        env.update(CHANNEL_EVENTS_TOPIC='lc4j.platform.channel.events',CHANNEL_DEDUP_DB_URL='jdbc:mysql://infra-mysql84:3306/lc4j_channel?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC',
                   CHANNEL_DEDUP_DB_USER='lc4j_channel_app',CHANNEL_DEDUP_DB_PASSWORD='${LC4J_CHANNEL_APP_PASSWORD}')
    if name=='interop-service':env.update(INTEROP_STATE_NAMESPACE='lc4j:platform:interop:a2a',INTEROP_CAPABILITY_REGISTRY_KEY='lc4j:platform:interop:capability-registry:v1')
    if name.startswith('knowledge-'):
        env.update(RAG_INGESTION_STORE='jdbc',RAG_INGESTION_DB_URL='jdbc:mysql://infra-mysql84:3306/lc4j_knowledge_ingestion?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC',
                   RAG_INGESTION_DB_USER='lc4j_ingest_app',RAG_INGESTION_DB_PASSWORD='${LC4J_INGEST_APP_PASSWORD}',
                   RAG_SOURCE_STORE='s3',RAG_SOURCE_S3_ENDPOINT='http://infra-minio:9000',RAG_SOURCE_S3_BUCKET='lc4j-knowledge-sources',
                   RAG_SOURCE_S3_ACCESS_KEY='lc4j-knowledge',RAG_SOURCE_S3_SECRET_KEY='${LC4J_S3_PASSWORD}',RAG_SOURCE_S3_PATH_STYLE='true',
                   RAG_REGISTRY_STORE='redis',QDRANT_HOST='lc4j-qdrant',RAG_ES_URIS='http://lc4j-elasticsearch:9200',RAG_ES_FAIL_FAST='true')
    if name=='agentscope-orchestrator':
        env.update(AGENT_CONFIRMATION_REDIS_URL='redis://lc4j:${LC4J_REDIS_PASSWORD}@infra-redis7:6379/0',
                   AGENT_SESSION_REDIS_URL='redis://lc4j:${LC4J_REDIS_PASSWORD}@infra-redis7:6379/0',
                   AGENT_CONFIRMATION_REDIS_NAMESPACE='lc4j:agentscope:tool-confirmation',
                   AGENT_SESSION_REDIS_NAMESPACE='lc4j:agentscope:agent-session')
    if name=='litellm':
        env.update(DATABASE_URL='postgresql://lc4j_litellm:${LC4J_PG_PASSWORD}@infra-postgres16:5432/lc4j_litellm',
                   REDIS_HOST='infra-redis7',REDIS_PORT='6379',REDIS_USERNAME='lc4j',REDIS_PASSWORD='${LC4J_REDIS_PASSWORD}',
                   OTEL_ENDPOINT='http://infra-otel-collector:4318/v1/traces')
        lines.append('    volumes: !override ["./litellm/config.dev-infra.yaml:/app/config.yaml:ro"]')
    lines.append('    environment: '+json.dumps(env,ensure_ascii=False))
lines.extend(['networks:','  dev-infra:','    external: true','    name: dev-infra'])
(ROOT/'deploy/docker-compose.dev-infra.yml').write_text('\n'.join(lines)+'\n')
base=(ROOT/'deploy/litellm/config.yaml').read_text().replace('namespace: "litellm.cache"','namespace: "lc4j:litellm.cache"\n    username: os.environ/REDIS_USERNAME\n    password: os.environ/REDIS_PASSWORD')
(ROOT/'deploy/litellm/config.dev-infra.yaml').write_text(base)
print('Generated dev-infra overlay without resolving credentials.')
