{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: platform-default-deny
  labels:
    app.kubernetes.io/name: platform-default-deny
    app.kubernetes.io/part-of: langchain4j-platform
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/part-of: langchain4j-platform
  policyTypes:
    - Ingress
    - Egress
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: platform-allow-required
  labels:
    app.kubernetes.io/name: platform-allow-required
    app.kubernetes.io/part-of: langchain4j-platform
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/part-of: langchain4j-platform
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app.kubernetes.io/part-of: langchain4j-platform
        {{- range .Values.networkPolicy.ingressNamespaces }}
        - namespaceSelector:
            matchLabels:
              {{- toYaml . | nindent 14 }}
        {{- end }}
  egress:
    - to:
        - podSelector:
            matchLabels:
              app.kubernetes.io/part-of: langchain4j-platform
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: kube-system
          podSelector:
            matchLabels:
              k8s-app: kube-dns
      ports:
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 53
    {{- if .Values.networkPolicy.allowPublicEgress }}
    - to:
        - ipBlock:
            cidr: 0.0.0.0/0
            except:
              {{- toYaml .Values.networkPolicy.deniedIpv4Cidrs | nindent 14 }}
        - ipBlock:
            cidr: ::/0
            except:
              {{- toYaml .Values.networkPolicy.deniedIpv6Cidrs | nindent 14 }}
    {{- end }}
    {{- range .Values.networkPolicy.allowedEgressCidrs }}
    - to:
        - ipBlock:
            cidr: {{ . | quote }}
    {{- end }}
{{- end }}
