CREATE TABLE IF NOT EXISTS ASYNC_TASK (
  TASK_ID VARCHAR(128) NOT NULL PRIMARY KEY,
  TENANT_ID VARCHAR(128) NOT NULL,
  USER_ID VARCHAR(128) NOT NULL,
  KIND VARCHAR(128) NOT NULL,
  STATUS VARCHAR(32) NOT NULL,
  INPUT_JSON MEDIUMTEXT,
  RESULT_JSON MEDIUMTEXT,
  ERROR_TEXT VARCHAR(2048),
  WEBHOOK_URL VARCHAR(1024),
  CREATED_AT BIGINT NOT NULL,
  UPDATED_AT BIGINT NOT NULL,
  FINISHED_AT BIGINT,
  LEASE_OWNER_ID VARCHAR(128),
  LEASE_EXPIRES_AT BIGINT,
  LEASE_EPOCH BIGINT NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS ASYNC_TASK_EVENT (
  TASK_ID VARCHAR(128) NOT NULL,
  SEQUENCE BIGINT NOT NULL,
  EVENT_KEY VARCHAR(128) NOT NULL,
  EVENT_NAME VARCHAR(128) NOT NULL,
  DATA_JSON MEDIUMTEXT,
  CREATED_AT BIGINT NOT NULL,
  WORKER_ID VARCHAR(128),
  PRIMARY KEY (TASK_ID, SEQUENCE)
);

CREATE TABLE IF NOT EXISTS ASYNC_TASK_WEBHOOK_OUTBOX (
  OUTBOX_ID VARCHAR(128) NOT NULL PRIMARY KEY,
  TASK_ID VARCHAR(128) NOT NULL,
  TENANT_ID VARCHAR(128) NOT NULL,
  TARGET_URL VARCHAR(1024) NOT NULL,
  TASK_STATUS VARCHAR(32) NOT NULL,
  PAYLOAD_JSON MEDIUMTEXT NOT NULL,
  STATUS VARCHAR(16) NOT NULL,
  ATTEMPTS INT NOT NULL DEFAULT 0,
  NEXT_ATTEMPT_AT BIGINT NOT NULL,
  LAST_ERROR VARCHAR(512),
  CLAIMED_BY VARCHAR(128),
  CLAIMED_UNTIL BIGINT,
  CREATED_AT BIGINT NOT NULL,
  UPDATED_AT BIGINT NOT NULL
);

CREATE TABLE IF NOT EXISTS ASYNC_TASK_LIFECYCLE_OUTBOX (
  EVENT_ID VARCHAR(160) NOT NULL PRIMARY KEY,
  TENANT_ID VARCHAR(64),
  PAYLOAD_JSON TEXT NOT NULL,
  STATUS VARCHAR(16) NOT NULL,
  ATTEMPTS INT NOT NULL DEFAULT 0,
  NEXT_ATTEMPT_AT BIGINT NOT NULL,
  LAST_ERROR VARCHAR(512),
  CLAIMED_BY VARCHAR(128),
  CLAIMED_UNTIL BIGINT,
  CREATED_AT BIGINT NOT NULL,
  UPDATED_AT BIGINT NOT NULL
);
