CREATE TABLE ASYNC_TASK_DISPATCH_LOCK (
  LOCK_ID INT NOT NULL PRIMARY KEY COMMENT '单调度互斥行标识, 固定为1',
  LAST_TENANT VARCHAR(128) NOT NULL DEFAULT '' COMMENT '轮转游标, 避免热租户持续占满空闲槽',
  LAST_CLAIM_AT BIGINT NOT NULL DEFAULT 0 COMMENT '最近领取毫秒时间'
) COMMENT='只读worker全局和租户配额串行判定锁';
INSERT INTO ASYNC_TASK_DISPATCH_LOCK (LOCK_ID, LAST_CLAIM_AT) VALUES (1, 0);
CREATE TABLE ASYNC_TASK_DISPATCH (
  TASK_ID VARCHAR(128) NOT NULL PRIMARY KEY COMMENT '同事务创建的中心任务ID',
  DEPARTMENT VARCHAR(256) COMMENT '已验签身份部门, 非输入参数',
  TRACE_ID VARCHAR(128) NOT NULL COMMENT '服务捕获的追踪ID',
  ATTEMPTS INT NOT NULL DEFAULT 0 COMMENT '领取次数, 包含崩溃接管',
  CREATED_AT BIGINT NOT NULL COMMENT '入队毫秒时间',
  FOREIGN KEY (TASK_ID) REFERENCES ASYNC_TASK(TASK_ID) ON DELETE CASCADE,
  INDEX IDX_DISPATCH_CREATED (CREATED_AT, TASK_ID)
) COMMENT='可恢复只读任务上下文, 不存JWT或确认授权';
CREATE INDEX IDX_ASYNC_DISPATCH_LEASE ON ASYNC_TASK (STATUS, LEASE_EXPIRES_AT, TENANT_ID, KIND);
